# Generated by Django 4.2.16 on 2024-09-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=256, unique=True)),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("valor_pedido_minimo", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="PedidoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="description",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="done",
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="nome",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_minima",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade",
            field=models.CharField(default="UN", max_length=16),
        ),
        migrations.CreateModel(
            name="ProdutoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
                ),
                ("lote", models.CharField(default="", max_length=32)),
                ("quantidade_disponivel", models.IntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoEntregaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("data_entrega_prevista", models.DateTimeField(blank=True, null=True)),
                (
                    "pedido_entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pedidoentrega",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fornecedor",
            ),
        ),
    ]
